import type { NextPage } from 'next'
import BurgerMenu from '../components/utils/BurgerMenu'
import DarkMode from '../components/utils/DarkMode'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        <link
          href='https://fonts.googleapis.com/css2?family=Mulish:wght@200;300;400;500;600;700;800;900&display=swap'
          rel='stylesheet'
        />
        <title>My Personal Website</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <DarkMode />
      <BurgerMenu />
      <div className='bg bg-cover bg-no-repeat bg-center w-screen h-screen flex items-center overflow-hidden p-3'>
        <div className='border-2 border-red-800 w-full font-muli text-white p-16'>
          <h1 className='text-6xl'>I'M Diajan</h1>
          <h2>I'M Diajan</h2>
          <p>
            In a professional context it often happens that private clients
            corder a publication to be made.
          </p>
          <h1>social</h1>
        </div>
      </div>
      <style jsx>{`
        .bg {
          background-image: url('https://retrina.com/demo/arshia/cv/assets/img/home-bg-3.jpg');
        }
      `}</style>
    </>
  )
}

export default Home
