import React from 'react'
import Head from 'next/head'
import Menu from '../components/generic/Menu'
import DarkMode from '../components/DarkMode'
import Chevrons from '../components/Chevrons'

interface Props {
  children: React.HTMLAttributes<HTMLElement>
}

const Main: React.FC<Props> = ({ children }) => {
  return (
    <div className='overflow-hidden'>
      <Head>
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        <link
          href='https://fonts.googleapis.com/css2?family=Mulish:wght@200;300;400;500;600;700;800;900&display=swap'
          rel='stylesheet'
        />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css'
          integrity='sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA=='
          crossOrigin='anonymous'
          referrerPolicy='no-referrer'
        />
        <title>My Personal Website</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <DarkMode />
      <div className='flex'>
        <Menu />
        <div className='flex-grow'>
          <div className='w-11/12 mx-auto'>{children}</div>
        </div>
      </div>
      <Chevrons />
    </div>
  )
}

export default Main
