import React from 'react'
import Head from 'next/head'
import Menu from '../components/generic/Menu'
import DarkMode from '../components/Switch'
import Chevrons from '../components/Chevrons'

interface Props {
  children: React.HTMLAttributes<HTMLElement>
}

const Main: React.FC<Props> = ({ children }) => {
  return (
    <div className='overflow-hidden bg-gray-200 font-muli'>
      <Head>
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        <link
          href='https://fonts.googleapis.com/css2?family=Mulish:wght@200;300;400;500;600;700;800;900&display=swap'
          rel='stylesheet'
        />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css'
          integrity='sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=='
          crossOrigin='anonymous'
          referrerPolicy='no-referrer'
        />
        <title>My Personal Website</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <DarkMode />
      <div className='flex'>
        <Menu />
        <div className='flex-grow'>
          <div className='w-11/12 mx-auto'>{children}</div>
        </div>
      </div>
      <Chevrons />
    </div>
  )
}

export default Main
